[package]
name = "RayTracerOneWeekend"
version = "0.1.0"
authors = ["Bombini"]
edition = "2021"

[profile.release]
opt-level = 3

[profile.dev]
opt-level = 0

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
rand = "0.9.0-alpha.1"
