on: [push, pull_request]

name: Rust

env:
  
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  windows:
    name: Check Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.80.0

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Check all
        run: cargo check --all-targets --all-features

      - name: Check RustTracer
        run: cargo check -p RustTracer
        
      - name: Build
        run: cargo build --verbose
